service: expressXRayPOC # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline